# -*- coding: utf-8 -*-
"""basic_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYZCGhG7JIhgXHnQMaaiy62uOaYNf94o

# 1. Python Codes - Basics

## 1.1. Lists
Python knows a number of compound data types, used to group together other values. The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.

### 1.1.1. Creating a *list* ?
"""

squares = [1, 4, 9, 16, 25]
squares

"""### 1.1.2. Slice & Index
Like strings (and all other built-in sequence types), lists can be indexed and sliced:
"""

print(squares[0])  # indexing returns the item

print(squares[-1])

print(squares[-3:])  # slicing returns a new list

"""### 1.1.3. Concatenation"""

squares = [1, 2, 3, 4, 5, 56]
squares + [36, 49, 64, 81, 100]

"""### 1.1.4. Mutuable List
* Unlike strings, which are immutable, **lists are a mutable type, i.e. it is possible to change their content**:
"""

cubes = [1, 8, 27, 65, 125]  # something's wrong here. The cube of 4 is 64, not 65!

cubes[3] = 4**3  # replace the wrong value
cubes

"""* We can also add new items at the end of the list, by using the ***list.append() method***"""

cubes = [1, 8, 27, 64, 125]
cubes.append(216)  # add the cube of 6
cubes.append(7 ** 3)  # and the cube of 7
cubes

"""* Simple assignment in Python never copies data. When you assign a list to a variable, the variable refers to the *existing list*. Any changes you make to the list through one variable will be seen through all other variables that refer to it.:"""

rgb = ["Red", "Green", "Blue"]
rgba = rgb
print(id(rgb) == id(rgba))  # they reference the same object

rgba.append("Alph")
print(rgb)

"""### 1.1.5. Shallow Copy
* All slice operations return a new list containing the requested elements. This means that the following slice returns a shallow copy of the list:
"""

#rgb = ["Red", "Green", "Blue"]
correct_rgba = rgba[:]
correct_rgba[-1] = "Alpha"
print(correct_rgba)
rgba

"""* Assignment to slices is also possible, and this can even change the size of the list or clear it entirely:"""

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(letters)

# replace some values
letters[2:5] = ['C', 'D', 'E']
print(letters)

# now remove them
letters[2:5] = []
print(letters)

# clear the list by replacing all the elements with an empty list
letters[:] = []
print(letters)

"""### 1.1.6.  Built-in function *len()*"""

letters = ['a', 'b', 'c', 'd']
len(letters)

"""### 1.1.7. Nest Lists
It is possible to nest lists (create lists containing other lists), for example:
"""

a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
print(x)

print(x[0])

print(x[0][1])

