m = int(input("Enter your marks: "))
print("You have entered...")
if m == 100: print("Grade: O")
elif 90 <= m < 100: print("Grade: E")
elif 80 <= m < 90: print("Grade: A")
elif 70 <= m < 80: print("Grade: B")
elif 60 <= m < 70: print("Grade: C")
elif 50 <= m < 60: print("Grade: D")
else: print("Grade: F")