lst = list('abcdefghijk')
print(lst)
print('length of the List: ',len(lst))
lst.append('l')
print(lst)
lst.extend(['m','n'])
print(lst)
lst.insert(0,"x")
print(lst)

print("Removing k...")
lst.remove("k")
print(lst)
# print('Removing 50')
# print(lst.remove(50)) Getting Error!!!
print('Deleting index 0...')
del lst[0]
print(lst)
print('poping...')
lst.pop()
print(lst)
print('Pop index 2')
lst.pop(2)
print(lst)
print('List clearing...')
lst.clear()
print(lst)
